# Generated by Django 4.1.5 on 2023-01-18 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.SmallIntegerField(choices=[(1, 'Gögüs'), (2, 'Arka Kol'), (3, 'Bacak'), (4, 'Omuz'), (5, 'Sirt'), (6, 'Ön Kol'), (7, 'Karin'), (8, 'Bel'), (9, 'Kardiyo')], default=1)),
                ('task', models.CharField(max_length=150)),
                ('description', models.CharField(max_length=300)),
                ('is_done', models.BooleanField(default=False)),
            ],
        ),
    ]
